name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive production artifact
        run: zip -r app.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .

      - name: Extract artifact
        run: unzip app.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YourAppName'  # Replace with your Azure Web App name
          slot-name: 'Production'
          package: .
